Create 01.1-Code_of_conduct.Rmd
microbiome/course_2022_oulu pull request #2
Opened 2022-06-06 10:27 UTC by shigdel

added code of conduct file

2022-06-06 16:56 UTC, TuomasBorman commented on 01.1-Code_of_conduct.Rmd
> +
I'm not sure if this does bullets.

You could add 

   - line, I think it does it ('-')

2022-06-06 16:57 UTC, TuomasBorman commented on 01.1-Code_of_conduct.Rmd
> +
These could be bolded

2022-06-06 16:57 UTC, TuomasBorman requested changes
You could add this all text to index.Rmd file. Check the book, index.Rmd contains 1 section

2022-06-06 17:00 UTC, TuomasBorman commented
Thanks!

2022-06-06 17:01 UTC, antagomir commented
Also @shigdel check locally if the rendering output looks OK. If unclear how to do, then more in Slack.

2022-06-06 17:04 UTC, TuomasBorman commented
https://github.com/microbiome/course_2022_oulu#rendering-the-book

this shoudl do it

2022-06-07 07:38 UTC, shigdel commented
> You could add this all text to index.Rmd file. Check the book, index.Rmd contains 1 section

i didnt see 1 section on index.Rmd

2022-06-07 08:03 UTC, antagomir commented
It is in _bookdown.yml

2022-06-15 17:12 UTC, antagomir commented
There is still a request. @shigdel can you take care of completing this one?

2022-06-17 20:27 UTC, antagomir commented
Replaced by #5

2022-06-17 20:27 UTC, closed without merging