code of conduct  with link
microbiome/course_2022_oulu pull request #5
Opened 2022-06-17 20:12 UTC by shigdel

here i have added the link to code of conduct

2022-06-17 20:25 UTC, antagomir requested changes
Kindly check the comments and modify accordingly. Pay attention that the rendered text is similar to the original version at https://bioconductor.github.io/bioc_coc_multilingual/

2022-06-17 20:25 UTC, antagomir commented on 01.1-codeofconduct.Rmd
> +    * community contributions
Thanks for adding the bullet points here (based on earlier PR and its requests). 

But we have other similar lists later in this text. Well could you add the bullet points in the other relevant places as well?

2022-06-17 20:25 UTC, antagomir commented on 01.1-codeofconduct.Rmd
> +Reporting
This seems to be a subtitle in the original text in 
https://bioconductor.github.io/bioc_coc_multilingual/

Can you check the original text, and make the appearance similar.. (titles are titles, bolding is bolding etc).

2022-06-18 08:06 UTC, TuomasBorman commented
Also this is not yet added to the course material? What would be a good place? Before acknowledgements? https://microbiome.github.io/course_2022_oulu/index.html#acknowledgments

2022-06-18 08:10 UTC, antagomir commented
> Also this is not yet added to the course material? What would be a good place? Before acknowledgements? https://microbiome.github.io/course_2022_oulu/index.html#acknowledgments

Just to check - in what sense it is not yet in the course material? (It is on the course website, or at least the link points there).

2022-06-18 08:14 UTC, TuomasBorman commented
I rendered the book and it was not included in the book. I can check again

2022-06-18 11:45 UTC, antagomir commented
@shigdel could you handle the feedback and commit the updates, so we can merge

2022-06-19 17:54 UTC, antagomir requested changes
Thanks - I do not see changes for the points that I asked in the review. Could you add and commit?

2022-06-19 17:54 UTC, antagomir commented on 01.1-codeofconduct.Rmd
> +    * community contributions
Hi @shigdel - this seems like not resolved yet?

2022-06-19 17:54 UTC, antagomir commented on 01.1-codeofconduct.Rmd
> +Reporting
This also

2022-06-28 14:57 UTC, antagomir commented
Can this be closed now with #9

2022-06-28 15:08 UTC, TuomasBorman commented
Yes

2022-06-28 15:08 UTC, closed without merging